FROM debian:stable

RUN apt-get update && apt-get install -y nginx

RUN rm /etc/nginx/sites-enabled/default

# Nginx config file generation
COPY ./sysadmin/configs/nginx/default-docker /etc/nginx/sites-enabled/default

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80 443